"""initalisering

Revision ID: f9e258402092
Revises: c9700379d591
Create Date: 2020-01-15 11:27:15.453458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e258402092'
down_revision = 'c9700379d591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'konkurrence', type_='foreignkey')
    op.drop_column('konkurrence', 'grunddata_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('konkurrence', sa.Column('grunddata_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'konkurrence', 'grunddata', ['grunddata_id'], ['id'])
    # ### end Alembic commands ###
